import assert from 'node:assert/strict';
import {createBackup,readBackup} from '../app/library.js';
import {renderAudio,evenVolume} from '../app/audio-processing.js';
const rate=24000;
const signal=Float32Array.from({length:rate*8},(_,i)=>(i<rate*4?.04:.5)*Math.sin(2*Math.PI*225*i/rate));
const original=signal.slice();
const enhanced=evenVolume([signal],rate)[0];
const rms=(a,start,end)=>Math.sqrt(a.slice(start,end).reduce((n,v)=>n+v*v,0)/(end-start));
assert.ok(rms(enhanced,rate*2,rate*3)>rms(signal,rate*2,rate*3)*1.5);
assert.ok(rms(enhanced,rate*6,rate*7)<rms(signal,rate*6,rate*7)*.7);
assert.deepEqual(signal,original);assert.ok(enhanced.every(v=>Number.isFinite(v)&&Math.abs(v)<=.951));
assert.ok(evenVolume([new Float32Array(rate)],rate)[0].every(v=>v===0));
const stereo=evenVolume([signal,Float32Array.from(signal,v=>v*.5)],rate);assert.ok(Math.abs(stereo[0][1000]*.5-stereo[1][1000])<1e-7);
const rendered=renderAudio([signal],rate,'echo',{start:1,end:3},()=>{},true);assert.equal(rendered.duration,2.39);assert.equal(new DataView(rendered.buffer).getUint32(24,true),rate);assert.deepEqual(signal,original);
const clip={id:'fixture-1',title:'中文录音 🎙',created:1720000000000,duration:8,microphone:'Test input',effect:'tune',trim:{start:1,end:7},enhance:true,peaks:[0,.2,1],blob:new Blob([renderAudio([signal],rate).buffer],{type:'audio/wav'})};
const archive=createBackup([clip]);const [restored]=await readBackup(archive);
assert.equal(restored.title,clip.title);assert.deepEqual(restored.trim,clip.trim);assert.equal(restored.enhance,true);assert.deepEqual(await restored.blob.arrayBuffer(),await clip.blob.arrayBuffer());
assert.deepEqual(await readBackup(createBackup([])),[]);
const mutate=async fn=>{const bytes=new Uint8Array(await archive.arrayBuffer()),len=new DataView(bytes.buffer).getUint32(8),data=JSON.parse(new TextDecoder().decode(bytes.slice(12,12+len)));fn(data);const header=new TextEncoder().encode(JSON.stringify(data)),prefix=new Uint8Array(12);prefix.set(bytes.slice(0,8));new DataView(prefix.buffer).setUint32(8,header.length);return new Blob([prefix,header,bytes.slice(12+len)]);};
for(const fn of [d=>d.version=2,d=>d.recordings[0].size=-1,d=>d.recordings[0].offset=10,d=>d.recordings[0].duration=null,d=>d.recordings[0].trim.end=100,d=>d.recordings[0].mime='text/html',d=>d.recordings.push(d.recordings[0]),d=>d.recordings[0].peaks=[null],d=>d.recordings[0].title='',d=>d.recordings[0].effect='bad'])await assert.rejects(readBackup(await mutate(fn)));
await assert.rejects(readBackup(archive.slice(0,archive.size-1)));await assert.rejects(readBackup(new Blob(['invalid'])));await assert.rejects(readBackup(new Blob([archive,'extra'])));
console.log('PASS: volume leveling, silence, stereo linkage, original preservation, trim + effect + enhancement, lossless Chinese backup round trip, and 13 malformed backup cases.');
